apiVersion: v1
kind: Service
metadata:
  name: my-wordpress-service
  labels:
    app: my-wordpress-service-app
spec:
  ports:
    - port: 80
  selector:
    app: my-wordpress-app
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-wordpress-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-wordpress-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-wordpress-app
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.9-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: my-mysql-service
        - name: WORDPRESS_DB_PASSWORD
          value: "123456789"
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
